### ISSUE TITLE
Parse File Fail Invalid escape sequence while reading a string On Line: 1129

### ISSUE THREAD

**Issue by linliaoy** [esrrhs/cLua#5]
1129行是这个：  ['\26'] = "\\Z",

**Comment by esrrhs** [comment]
应该是go的库太老了，更新试试看

**Comment by linliaoy** [comment]
"github.com/milochristiansen/lua/ast" 这个吗？

**Comment by linliaoy** [comment]
[https://github.com/milochristiansen/lua/issues/37](url)
我去这里问了一下，要转义，有点不太友好

**Comment by linliaoy** [comment]
[https://github.com/linliaoy/cLua-skynet.git](url)  改了一版用于skynet

**Comment by linliaoy** [comment]
给点意见
